// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func Class(v string) func(*templ.Attributes) {
	return func(attrs *templ.Attributes) {
		attr := *attrs
		class := attr["class"].(string) + " " + v
		attr["class"] = class
	}
}

func IFCN(classNames []string) string {
	class := ""
	for _, cn := range classNames {
		class = class + " " + cn
	}
	return class
}

func IFF(cond bool, value string) string {
	if cond {
		return value
	}
	return ""
}
